apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
    app: ktor-api-service
    env: local
spec:
  claimRef:
    namespace: ktor
    name: postgres-volume-claim
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/yangwang/development/storage/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    env: local
    app: ktor-api-service
spec:
  volumeName: postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi